CREATE TABLE "departamentos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "municipios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "departamento_id" int NOT NULL,
  "nombre" varchar(50) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "comunidades" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "municipio_id" int NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "auth_users" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "perfiles" (
  "id" uuid PRIMARY KEY,
  "nombre_completo" varchar(150) NOT NULL,
  "telefono" varchar(20),
  "avatar_url" text,
  "municipio_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "organizaciones" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "nombre" varchar(150) NOT NULL,
  "tipo_institucion" varchar(50) NOT NULL,
  "municipio_id" int NOT NULL,
  "creador_id" uuid NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "organizacion_miembros" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "organizacion_id" uuid NOT NULL,
  "perfil_id" uuid NOT NULL,
  "rol_interno" varchar(50) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "comunicados" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "organizacion_id" uuid NOT NULL,
  "titulo" varchar(200) NOT NULL,
  "contenido" text NOT NULL,
  "tipo_aviso" varchar(50) NOT NULL,
  "fecha_publicacion" timestamp DEFAULT (now())
);

CREATE TABLE "deportes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL,
  "codigo_clave" varchar(20) UNIQUE NOT NULL,
  "tipo_competencia" varchar(30) NOT NULL
);

CREATE TABLE "acreditaciones_mesa" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "perfil_id" uuid NOT NULL,
  "organizacion_id" uuid NOT NULL,
  "deporte_id" int NOT NULL,
  "estado_aprobacion" varchar(20) NOT NULL DEFAULT 'pendiente',
  "fecha_emision" timestamp DEFAULT (now())
);

CREATE TABLE "equipos" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "nombre" varchar(100) NOT NULL,
  "deporte_id" int NOT NULL,
  "comunidad_id" int NOT NULL,
  "administrador_id" uuid NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "atletas" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "nombre_completo" varchar(150) NOT NULL,
  "identificacion" varchar(50),
  "equipo_id" uuid,
  "perfil_id" uuid UNIQUE,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "torneos" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "nombre" varchar(150) NOT NULL,
  "categoria_territorial" varchar(50) NOT NULL,
  "deporte_id" int NOT NULL,
  "organizacion_id" uuid NOT NULL,
  "temporada" varchar(20) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "torneo_inscripciones" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "torneo_id" uuid NOT NULL,
  "equipo_id" uuid,
  "atleta_id" uuid,
  "estado_inscripcion" varchar(20) NOT NULL DEFAULT 'aprobado',
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "encuentros" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "torneo_id" uuid NOT NULL,
  "anotador_id" uuid NOT NULL,
  "fecha_hora" timestamp NOT NULL,
  "sede_instalacion" varchar(150) NOT NULL,
  "estado_encuentro" varchar(30) NOT NULL DEFAULT 'programado',
  "transmision_url" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "competidores_encuentro" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "encuentro_id" uuid NOT NULL,
  "equipo_id" uuid,
  "atleta_id" uuid,
  "rol_posicion_etiqueta" varchar(50),
  "puntuacion_final" numeric(10,2) DEFAULT 0,
  "es_ganador" boolean DEFAULT false
);

CREATE TABLE "participantes_acta" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "competidor_encuentro_id" uuid NOT NULL,
  "atleta_id" uuid NOT NULL,
  "posicion_rol" varchar(50),
  "es_titular" boolean DEFAULT true
);

CREATE TABLE "periodos_marcador" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "competidor_encuentro_id" uuid NOT NULL,
  "numero_periodo" int NOT NULL,
  "puntos_acumulados" numeric(10,2) DEFAULT 0
);

CREATE TABLE "metricas_catalogo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "deporte_id" int NOT NULL,
  "clave_metrica" varchar(30) NOT NULL,
  "nombre_visible" varchar(100) NOT NULL,
  "tipo_dato" varchar(20) NOT NULL,
  "ambito" varchar(30) NOT NULL
);

CREATE TABLE "valores_metricas_encuentro" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "encuentro_id" uuid NOT NULL,
  "atleta_id" uuid NOT NULL,
  "metrica_id" int NOT NULL,
  "valor_registrado" numeric(10,2) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "organizaciones"."tipo_institucion" IS 'Comision, Alcaldia, IND, Liga';

COMMENT ON COLUMN "organizacion_miembros"."rol_interno" IS 'Admin, Organizador, Comisionado';

COMMENT ON COLUMN "comunicados"."tipo_aviso" IS 'General, Suspension, Convocatoria';

COMMENT ON COLUMN "deportes"."codigo_clave" IS 'beisbol, futbol, boxeo, atletismo';

COMMENT ON COLUMN "deportes"."tipo_competencia" IS 'COLECTIVO, INDIVIDUAL_DUELO, CIRCUITO_MARCA';

COMMENT ON COLUMN "acreditaciones_mesa"."estado_aprobacion" IS 'pendiente, aprobado, rechazado';

COMMENT ON COLUMN "atletas"."equipo_id" IS 'Opcional si es disciplina de combate/individual';

COMMENT ON COLUMN "atletas"."perfil_id" IS 'Opcional si el atleta reclama su ficha';

COMMENT ON COLUMN "torneos"."categoria_territorial" IS 'Campesina, Municipal, Departamental';

COMMENT ON COLUMN "encuentros"."estado_encuentro" IS 'programado, en_curso, finalizado, suspendido';

COMMENT ON COLUMN "competidores_encuentro"."equipo_id" IS 'Presente si es competencia colectiva';

COMMENT ON COLUMN "competidores_encuentro"."atleta_id" IS 'Presente si es duelo 1v1 (boxeo)';

COMMENT ON COLUMN "competidores_encuentro"."rol_posicion_etiqueta" IS 'Lado A, Lado B, Esquina Roja, Carril 1';

COMMENT ON COLUMN "periodos_marcador"."numero_periodo" IS 'Inning 1..9, Tiempo 1..2, Round 1..12';

COMMENT ON COLUMN "metricas_catalogo"."clave_metrica" IS 'AB, H, HR, ERA, GOLES, ASISTENCIAS, ROUNDS';

COMMENT ON COLUMN "metricas_catalogo"."tipo_dato" IS 'ENTERO, DECIMAL, TEXTO';

COMMENT ON COLUMN "metricas_catalogo"."ambito" IS 'OFENSIVA, DEFENSIVA, COMBATE, GENERAL';

ALTER TABLE "municipios" ADD FOREIGN KEY ("departamento_id") REFERENCES "departamentos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comunidades" ADD FOREIGN KEY ("municipio_id") REFERENCES "municipios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "auth_users" ADD FOREIGN KEY ("id") REFERENCES "perfiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "perfiles" ADD FOREIGN KEY ("municipio_id") REFERENCES "municipios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "organizaciones" ADD FOREIGN KEY ("municipio_id") REFERENCES "municipios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "organizaciones" ADD FOREIGN KEY ("creador_id") REFERENCES "perfiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "organizacion_miembros" ADD FOREIGN KEY ("organizacion_id") REFERENCES "organizaciones" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "organizacion_miembros" ADD FOREIGN KEY ("perfil_id") REFERENCES "perfiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comunicados" ADD FOREIGN KEY ("organizacion_id") REFERENCES "organizaciones" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "acreditaciones_mesa" ADD FOREIGN KEY ("perfil_id") REFERENCES "perfiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "acreditaciones_mesa" ADD FOREIGN KEY ("organizacion_id") REFERENCES "organizaciones" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "acreditaciones_mesa" ADD FOREIGN KEY ("deporte_id") REFERENCES "deportes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipos" ADD FOREIGN KEY ("deporte_id") REFERENCES "deportes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipos" ADD FOREIGN KEY ("comunidad_id") REFERENCES "comunidades" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipos" ADD FOREIGN KEY ("administrador_id") REFERENCES "perfiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "atletas" ADD FOREIGN KEY ("equipo_id") REFERENCES "equipos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "perfiles" ADD FOREIGN KEY ("id") REFERENCES "atletas" ("perfil_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "torneos" ADD FOREIGN KEY ("deporte_id") REFERENCES "deportes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "torneos" ADD FOREIGN KEY ("organizacion_id") REFERENCES "organizaciones" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "torneo_inscripciones" ADD FOREIGN KEY ("torneo_id") REFERENCES "torneos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "torneo_inscripciones" ADD FOREIGN KEY ("equipo_id") REFERENCES "equipos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "torneo_inscripciones" ADD FOREIGN KEY ("atleta_id") REFERENCES "atletas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "encuentros" ADD FOREIGN KEY ("torneo_id") REFERENCES "torneos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "encuentros" ADD FOREIGN KEY ("anotador_id") REFERENCES "perfiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "competidores_encuentro" ADD FOREIGN KEY ("encuentro_id") REFERENCES "encuentros" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "competidores_encuentro" ADD FOREIGN KEY ("equipo_id") REFERENCES "equipos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "competidores_encuentro" ADD FOREIGN KEY ("atleta_id") REFERENCES "atletas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "participantes_acta" ADD FOREIGN KEY ("competidor_encuentro_id") REFERENCES "competidores_encuentro" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "participantes_acta" ADD FOREIGN KEY ("atleta_id") REFERENCES "atletas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "periodos_marcador" ADD FOREIGN KEY ("competidor_encuentro_id") REFERENCES "competidores_encuentro" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "metricas_catalogo" ADD FOREIGN KEY ("deporte_id") REFERENCES "deportes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "valores_metricas_encuentro" ADD FOREIGN KEY ("encuentro_id") REFERENCES "encuentros" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "valores_metricas_encuentro" ADD FOREIGN KEY ("atleta_id") REFERENCES "atletas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "valores_metricas_encuentro" ADD FOREIGN KEY ("metrica_id") REFERENCES "metricas_catalogo" ("id") DEFERRABLE INITIALLY IMMEDIATE;
